id: P08039E7A
initial_creation_type: ocr
source_metadata:
  volumes:
    6310a9d3dcff442ca82be08c3eb379a9:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: རིན་པོ་ཆེ་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
